spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/lake?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: yang531560
mybatis:
   mapperLocations: classpath:/mapper/tpl/*.xml,classpath:/mapper/extend/*.xml
